export const staffdata = [
    {
    id: 1,
    name: "Mawlana Muhammad Ismayeel", 
    designation: "Najim_e_Emtihan", 
    contact_no: "01913500453", 
    e_mail: "haiatululya@gmail.com", 
    room_no: 301
}, 
{
    id: 2,
    name: "Mawlana Md Osiur Rahman", 
    designation: "Office Secretary", 
    contact_no: "01305656703", 
    e_mail: "osiur2@gmail.com", 
    room_no: 201,
    image: "mdosiurrahman.jpg",
},
{
    id: 3,
    name: "Mawlana Md Abdul Malik", 
    designation: "Head of Accounts", 
    contact_no: "01935650801", 
    e_mail: "haiatululya@gmail.com", 
    room_no: 203
},
{
    id: 4,
    name: "Md Sharif Hossain", 
    designation: "Senior Assistent", 
    contact_no: "01305656706", 
    e_mail: "haiatululya@gmail.com", 
    room_no: 302
},
{
    id: 5,
    name: "Mawlana MD Aliullah Khan.",
    father: "MD. Idris Khan.",
    mother: "Laili Begum.",
    present_address: "39 rosulpur, Donia 1236, Jatrabari, Dakha.",
    permanent_ddress: "Gandra ,Gandra 3519, Muradnagar, comilla.",
    academic_achievement: "Dawra-e-Hadis.",
    languages_skills: "Bengali, Arabic, English & Urdu.",
    Designation: "Senior Assistant", 
    contact_no: "01674014986", 
    e_mail: "aliullahk94@gmail.com", 
    room_no: 303
},
{
    id: 6,
    name: "Mawlana Ahmadullah Farhan",
    father: "Md. Hasanur Rahman",
    mother: "Kamrun Nahar Begum",
    present_address: "Kazla, Jatrabari, Dhaka",
    permanent_ddress: "Vill: Pingalia, post and Thana: Kasiani, Zila: Gopalganj",
    academic_achievement: "Dawra-e-Hadis.",
    languages_skills: "Bengali, Arabic, English & Urdu.",
    Designation: "Senior Assistant", 
    contact_no: "01681-681201", 
    e_mail: "mewfaru@gmail.com", 
    room_no: 203
},
{
    id: 7,
    name: "Mawlana Mohammad Abdul Mazed",
    father: "Mohammad Ali Khan",
    mother: "Taslima Akter",
    present_address: "G.P.Cha-211/1, T.B.Gate, Mohakhali, Banani, Dhaka-1213",
    permanent_ddress: "G.P.Cha-211/1, T.B.Gate, Mohakhali, Banani, Dhaka-1213",
    academic_achievement: "Dawra-e-Hadis.",
    languages_skills: "Bengali, Arabic, English & Urdu.",
    Designation: "Computer Operator", 
    contact_no: "01923-114855", 
    e_mail: "mazedmahmud333@gmail.com", 
    room_no: 303
},
{
    id: 8,
    name: "Mawlana Abdullah Rashid",
    father: "",
    mother: "",
    present_address: "",
    permanent_ddress: "",
    academic_achievement: "Dawra-e-Hadis.",
    languages_skills: "Bengali, Arabic, English & Urdu.",
    Designation: "Computer Operator", 
    contact_no: "", 
    e_mail: "", 
    room_no: 302
},
{
    id: 9,
    name: "Mawlana Mahmud Said",
    father: "Sayed Ahmed",
    mother: "Sadia Begum",
    present_address: "Dogair, Sarulia, Demra, Dhaka",
    permanent_ddress: "Chapila, Forokkabad, Chandpur, Chandpur",
    academic_achievement: "Dawra-e-Hadis.",
    languages_skills: "Bengali, Arabic, English & Urdu.",
    Designation: "Computer Operator", 
    contact_no: "01676-619225", 
    e_mail: "mahmudsaide@yahoo.com", 
    room_no: 302
},
{
    id: 10,
    name: "Mawlana Omar Faruk",
    father: "Abdus Samad",
    mother: "Sajeda Begum",
    present_address: "80/e  polaspiur, Donia, Kodomtoli, Dhaka",
    permanent_ddress: "80/e  polaspiur, Donia, Kodomtoli, Dhaka",
    academic_achievement: "Dawra-e-Hadis.",
    languages_skills: "Bengali, Arabic, English & Urdu.",
    Designation: "Computer Operator", 
    contact_no: "01675497066", 
    e_mail: "omarfaruk01245@gmail.com", 
    room_no: 200
},
{
    id: 11,
    name: "Mawlana Md.Taz Uddin",
    father: "Sheikh hamad",
    mother: "Nur Jahan begum",
    present_address: "House No:77, Road No:3, Block-G, Banasree, Dhaka",
    permanent_ddress: "Shamergoan, Kazirkhil, Shenbag,Noakhli",
    academic_achievement: "Dawra-e-Hadis.",
    languages_skills: "Bengali, Arabic, English & Urdu.",
    Designation: "Computer Operator", 
    contact_no: "01628-854849", 
    e_mail: "tazuddin4@gmail.com", 
    room_no: 302
},
{
    id: 12,
    name: "HAFEJE NAZRUL ISLAM",
    father: "LATE ABDUL MANNAN",
    mother: "LATE HASINA BEGUM",
    present_address: "102/D, NAYA POLTON",
    permanent_ddress: "ROWHA, SUAPUR, DHAMRAI, DHAKA",
    academic_achievement: "HAFEJE QURAN.",
    languages_skills: "Bengali, Arabic, English & Urdu.",
    Designation: "Computer Operator", 
    contact_no: "01732224212", 
    e_mail: "pmpublication78@gmail.com", 
    room_no: 302
},
{
    id: 13,
    name: "Mawlana Md Shoaeeb",
    father: "Md Abul Kashem",
    mother: "Jubaida khanom",
    present_address: "h# Uttara Pubali Gov Quarters, Circuit house road,Ramna:1217, Dhaka",
    permanent_ddress: "Char Bishnopur, Sadarpur, Faridpur",
    academic_achievement: "HAFEJE, Dawra-e-Hadis.",
    languages_skills: "Bengali, Arabic, English & Urdu.",
    Designation: "Computer Operator", 
    contact_no: "01615650992", 
    e_mail: "shoaeebmew.12345@gmail.com", 
    room_no: 302
},
{
    id: 14,
    name: "Md. Habibur Rhaman",
    father: "Md. Arobe Ali Bapary",
    mother: "Mst. Fazilat Neasa",
    present_address: "Village-Rayerbagh, post- Matuail, p.s- Kodomtoly, dist- Dhaka",
    permanent_ddress: "Village-Sheakhergaon, post- Luterchor, p.s- Meghna, dist- Comilla",
    academic_achievement: "SSC & HSC",
    languages_skills: "Bengali, Arabic, English & Urdu.",
    Designation: "ASSistent Computer Operator", 
    contact_no: "01832-237179", 
    e_mail: "habibhm660@gmail.com", 
    room_no: 302
},
]

